Site_Trades/Models/ErrorViewModel.cs
namespace Site_Trades.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Site_Trades/Models/RegLog/ForLogin.cs
using Site_Trades.ViewModels;

namespace Site_Trades.Models.RegLog;

public static class ForLogin
{
    public static List<LoginViewModel> LogUsers = new List<LoginViewModel>();
   public static void Add( LoginViewModel user)
    {
        LogUsers.Add(user);
    }

   public static List<double> Profit = new List<double>();
   
   public static List<int> CountTrades = new List<int>();
   
   public static List<int> ProfitTrades = new List<int>();
   
   public static List<int> LoseTrades = new List<int>();
   
   
   
}

Site_Trades/Models/RegLog/Register.cs
namespace Site_Trades.Models.RegLog
{
    public class Register
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public bool IsRegisted { get; set; }
    }
}

Site_Trades/Models/Trade.cs
using System.ComponentModel.DataAnnotations;

namespace Site_Trades.Models
{
    public class Trade
    {
        public int Id { get; set; }
        
        [Required]
        [MaxLength(50)]
        [MinLength(2)]
        public string Name { get; set; }

        [Required]
        public double Marzha { get; set; }

        [Required]
        public double Profit { get; set; }
        
        [Required]
        public DateTime Date { get; set; }

        public string? Email { get; set; }
    }
}

Site_Trades/ViewModels/LoginViewModel.cs
namespace Site_Trades.ViewModels;

public class LoginViewModel
{
    public int Id { get; set; }
    
    public string Name { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
}

Site_Trades/Controllers/EnterController.cs
using Microsoft.AspNetCore.Mvc;

namespace Site_Trades.Controllers;

public class EnterController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Site_Trades/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Site_Trades.Models;
using System.Diagnostics;

namespace Site_Trades.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Site_Trades/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Site_Trades.Models.RegLog;
using Site_Trades.Services.Trade;

namespace Site_Trades.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ITradeService _service;

        public ProfileController(ITradeService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            ForLogin.Profit.Add(_service.CountProfit());
            ForLogin.CountTrades.Add(_service.CountTrades());
            ForLogin.ProfitTrades.Add(_service.ProfitTrades());
            ForLogin.LoseTrades.Add(_service.LoseTrades());
            
            return View();
        }
    }
}



//Створити нову табличку в базі даних, де буде тільки ім'я + фаміля + емаіл і все, по кнопці регестрація і туди додавати ті значення,
// а потім вже витягувати саме з цієї таблички значення, які на потрібні

Site_Trades/Controllers/RegLog/ErrorLogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Site_Trades.Controllers.RegLog;

public class ErrorLogController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Site_Trades/Controllers/RegLog/LogOutController.cs
using Microsoft.AspNetCore.Mvc;
using Site_Trades.Models.RegLog;

namespace Site_Trades.Controllers.RegLog;

public class LogOutController : Controller
{
    // GET
    public IActionResult Index()
    {
        ForLogin.LogUsers.Clear();
        ForLogin.CountTrades.Clear();
        ForLogin.Profit.Clear();
        ForLogin.LoseTrades.Clear();
        ForLogin.ProfitTrades.Clear();
        
        
        return RedirectToAction("Index", "Login");
    }
}

Site_Trades/Controllers/RegLog/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Site_Trades.Data;
using Site_Trades.Models.RegLog;
using Site_Trades.Services;
using Site_Trades.ViewModels;
using System.Linq;

namespace Site_Trades.Controllers.RegLog;

public class LoginController : Controller
{
    private readonly IService _service;

    public LoginController(IService service)
    {
        _service = service;
    }
    
    // GET
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(LoginViewModel user)
    {
        if(_service.GetByEmail(user) == true)
        {
            return RedirectToAction("Index", "Home");
        }

        return RedirectToAction("Index", "ErrorLog");

    }
}

Site_Trades/Controllers/RegLog/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Site_Trades.Models.RegLog;
using Site_Trades.Services;

namespace Site_Trades.Controllers.RegLog
{
    public class RegisterController : Controller
    {
        private readonly IService _service;

        public RegisterController(IService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Register user)
        {
            user.IsRegisted= true;
            await _service.Add(user);

            return RedirectToAction("Index", "Login");
        }
    }
}

Site_Trades/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using Site_Trades.Models;
using Site_Trades.Models.RegLog;
using Site_Trades.Services.Trade;

namespace Site_Trades.Controllers
{
    public class TradeController : Controller
    {
        private ITradeService _service;

        public TradeController(ITradeService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Trade trade)
        {
            
            
            //if (!ModelState.IsValid)
            //{
            //    return View(trade);
            //}
            string email = "";

            foreach (var item in ForLogin.LogUsers)
            {
                email = item.Email;
            }


            trade.Email = email;
            await _service.AddTrade(trade);
            
            
            return RedirectToAction("Index", "Home");
        }
    }
}

Site_Trades/Views/Enter/Index.cshtml
@using Site_Trades.Models.RegLog



@{
    ViewData["Title"] = "Початок";
}

<link rel="stylesheet" href="css/site.css" asp-append-version="true"/>

<body>
    <div class="block-btns">
        <a asp-controller="Login" asp-action="Index" class="btn btn-gradient">Уввійти</a>
        <a asp-controller="Register" asp-action="Index" class="btn btn-gradient">Зареєструватися</a>
    </div>

    
</body>

Site_Trades/Views/ErrorLog/Index.cshtml
@{
    ViewData["Title"] = "Помилка при вході";
}

<div class="modal2">
        <div class="modal-window2">
            <h1>Не правильний пароль або почта, будь ласка, перевірте всі данні уважніше</h1>
            
            <a asp-controller="Login" asp-action="Index" class="btn-close"></a>
      
        </div>веч
        
        <div class="overlay2"></div>
</div>

Site_Trades/Views/Home/Index.cshtml
@using Site_Trades.ViewModels
@using Site_Trades.Models.RegLog
@model Site_Trades.Models.RegLog.Register



@{
    ViewData["Title"] = "Головна";
}

<header>
    <div class="header">

        <div class="header__container">
            <img class="header__logo" />

            <div class="header__navigation">
                <nav class="header__menu menu">
                    <ul class="menu__body">
                        <li class="menu__item">
                            <a asp-controller="Home" asp-action="Index" class="menu__link">Про сайт</a>
                            <a asp-controller="Trade" asp-action="Index" class="menu__link">Додати угоду</a>
                            <a asp-controller="Profile" asp-action="Index" class="menu__link" asp-route-id="">Мій профіль</a>
                        </li>
                    </ul>
                </nav>

            </div>
        </div>

    </div>
</header>


<div class="title">
    <h1 class="title-main">Для чого цей сайт ?</h1>
</div>

<div class="block">
    <div class="ltext">
        <div class="left-text">
            <p class="text-left">
                Ну спочатку можна сказати, що цей сайт для трейдерів.
                Саме цей сайт допоможе трейдерам слідкувати за їхніми угодами.
                Є багато фішек на цьому сайті, щоб полегшити життя трейдерам.
            </p>
        </div>
    </div>

    <div class="ctext">
        <div class="center-text">
            <p class="text-center">
                На цьому сайті трейдер зможе додати свою угоду.
                Записати свій профіт або збиток.
                Можна подивитися свою статистику.
                Крутий сайт з крутими фішками для трейдерів!


            </p>
        </div>
    </div>
</div>




<footer class="footer">
    Matok Company
</footer>

Site_Trades/Views/Login/Index.cshtml
@using Site_Trades.Models.RegLog
@model Site_Trades.ViewModels.LoginViewModel


@{
    ViewData["Title"] = "Вхід у аккаунт";
}

<link rel="stylesheet" href="css/register.css" asp-append-version="true" />


  <header>
        <div class="header">

            <div class="header__container">
                <img class="header__logo" />

                <div class="header__navigation">
                    <nav class="header__menu menu">
                        <ul class="menu__body">
                            <li class="menu__item">
                                <a asp-controller="Home" asp-action="Index" class="menu__link">Про сайт</a>
                                <a asp-controller="Trade" asp-action="Index" class="menu__link">Додати угоду</a>
                                <a asp-controller="Profile" asp-action="Index" class="menu__link" asp-route-id="">Мій профіль</a>
                            </li>
                        </ul>
                    </nav>

                </div>
            </div>

        </div>

    </header>





<div class="block-form">
    <div class="container3">
        <form class="form-reg" method="POST">
            <h2>Вхід в аккаунт</h2>

            <div class="form-group">
                <label class="email-title">Ім'я:</label>
                <input type="text" asp-for="Name"  required >
            </div>            
            
            <div class="form-group">
                <label class="email-title">Почта:</label>
                <input type="email" asp-for="Email"  required >
            </div>
            <div class="form-group">
                <label class="password-title">Пароль:</label>
                <input type="password" asp-for="Password" required >
            </div>
            <div class="form-group">
                <button class="btn-reg" asp-controller="Login" asp-action="Index">

                     Уввійти
                </button>
            </div>
        </form>
    </div>
</div>

Site_Trades/Views/Register/Index.cshtml
@using Site_Trades.Models.RegLog;
@model Register


@{
    ViewData["Title"] = "Реєстрація";
}

<link rel="stylesheet" href="css/register.css" asp-append-version="true" />


  <header>
        <div class="header">

            <div class="header__container">
                <img class="header__logo" />

                <div class="header__navigation">
                    <nav class="header__menu menu">
                        <ul class="menu__body">
                            <li class="menu__item">
                                <a asp-controller="Home" asp-action="Index" class="menu__link">Про сайт</a>
                                <a asp-controller="Trade" asp-action="Index" class="menu__link">Додати угоду</a>
                                <a asp-controller="Profile" asp-action="Index" class="menu__link" asp-route-id="">Мій профіль</a>
                            </li>
                        </ul>
                    </nav>

                </div>
            </div>

        </div>

    </header>


<div class="block-form">
    <div class="container2">
        <form class="form-reg" method="POST">
            <h2>Регестрація</h2>
            <div class="form-group">
                <label class="fname-title">Ім'я:</label>
                <input type="text" asp-for="FirstName" required>
            </div>
            <div class="form-group">
                <label class="sname-title">Прізвище:</label>
                <input type="text" asp-for="SecondName" required>
            </div>
            <div class="form-group">
                <label class="email-title">Почта:</label>
                <input type="email" id="email" asp-for="Email" name="email" required>
            </div>
            <div class="form-group">
                <label class="password-title">Пароль:</label>
                <input type="password" asp-for="Password" required>
            </div>
            <div class="form-group">
                <button class="btn-reg" asp-controller="Register" asp-action="Index">Зареєструватися</button>
            </div>
        </form>
    </div>
</div>

Site_Trades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trades</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tektur:wght@500&display=swap" rel="stylesheet">
</head>
<body>
  





    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Site_Trades/Views/Trade/Index.cshtml
@model Trade

@{
    ViewData["Title"] = "Додати угоду";
}

<link rel="stylesheet" href="css/profile.css" asp-append-version="true" />
<link rel="stylesheet" href="css/trade.css" asp-append-version="true" />


  <header>
        <div class="header">

            <div class="header__container">
                <img class="header__logo" />

                <div class="header__navigation">
                    <nav class="header__menu menu">
                        <ul class="menu__body">
                            <li class="menu__item">
                                <a asp-controller="Home" asp-action="Index" class="menu__link">Про сайт</a>
                                <a asp-controller="Trade" asp-action="Index" class="menu__link">Додати угоду</a>
                                <a asp-controller="Profile" asp-action="Index" class="menu__link" asp-route-id="">Мій профіль</a>
                            </li>
                        </ul>
                    </nav>

                </div>
            </div>

        </div>

    </header>


<h1 class="title-trade">Додати угоду</h1>




<div class="input-block">
    <div class="input-container">
        <form  class="form-trade" method="post">
            <input asp-for="Name" type="text" class="styled-input" placeholder="Назва крипти">
            <p></p>

            <input asp-for="Marzha" type="text" class="styled-input" placeholder="Маржа $">
            <p></p>

            <input asp-for="Profit" type="text" class="styled-input" placeholder="Профіт у %">
            <p></p>

            <input type="date"  asp-for="Date"  class="styled-input" name="Date" id="davaToday"> 
            <p></p>

            <button asp-controller="Trade" asp-action="Index" class="cool-button">Додати трейд</button>
        </form>
    </div>
</div>


<script>document.getElementById("davaToday").valueAsDate = new Date();</script>